### PR TITLE
Fix some naki is not shown in the review result

### LINKED ISSUE #47: Missing turn in replay examination
The Majsoul paipu is https://game.maj-soul.com/1/?paipu=220312-b4481a3d-57c0-4d89-b096-d7dd9dd7d837_a19427114

I followed the instruction [here](https://github.com/Equim-chan/akochan-reviewer/blob/master/mjsoul.adoc) and used tempermonkey to download the paipu above. I tried to use akochan-reviewer to analyse it, using the command `.\akochan-reviewer.exe -i .\2022_3_12_Gold_Room_South.json -n 0.1 --pt 110,50,-10,-130 -a 3 -k S1`, but found the 2nd turn was skipped when I pon 7m.

Image

### PR DESCRIPTION
**Pull request by JaySon-Huang**
## Problem Summary
close #47 
Under some situations, when another player discards a tile the target player can naki. Akochan give no suggestion and no pt expectations. Current the reviewer will skip the naki junme by accident under these situations.
```
> {"type":"dahai","actor":1,"pai":"7m","tsumogiri":false}
reviewing kyoku=4 honba=0 junme=1 (23.64%)
< [{"moves": [{"actor": 3, "type": "none"}], "review": {}}]
```

## What's changed
Check the next action, if the target_actor naki, continues to review the action

Signed-off-by: JaySon-Huang <tshent@qq.com>

### CODE REVIEW

File: src/review.rs [hunk 1]
```diff
@@ -324,8 +333,8 @@ pub fn review(review_args: &ReviewArgs) -> Result<Review> {
                 }
             }
         } else {
-            // Ditto.
-            (1., Acceptance::Agree)
```
Comment (JaySon-Huang) [inline src/review.rs:328]: I'm not sure why it is `Agree`

Comment (Equim-chan) [reply src/review.rs:328]: When akochan runs in rule-based mode (high shanten), it will not calculate the expected pt.

File: convlog/tests/testdata/confusing_nakis_7.json [hunk 2]
```diff
@@ -0,0 +1 @@
+{"log":[[[4,0,0],[30200,29600,23600,16600],[24],[34],[13,13,19,27,28,32,35,35,38,39,43,44,47],[47,44,22,"c292728",12,26,21],[44,60,43,22,32,19,60],[12,13,17,19,21,22,23,23,25,32,33,34,36],[31,24,18,24,11,29],[19,17,60,36,"r34",60],[14,16,25,26,27,28,29,31,36,38,39,43,46],[34,15,46,19,13],[43,46,60,60,31],[11,17,17,21,52,25,29,31,35,36,38,39,45],[46,"17p1717",26,32,11,26],[11,21,29,46,45,11],["和了",[-2600,3600,0,0],[1,0,1,"40符2飜2600点","Riichi(1飜)","Dora(1飜)","Ura Dora(0飜)"]]]],"rule":{"disp":"Gold Room South","aka53":1,"aka52":1,"aka51":1},"name":["A","B","C","target"],"title":["",""]}
```
Comment (Equim-chan) [inline convlog/tests/testdata/confusing_nakis_7.json:1]: You need to modify convlog/tests/testdata/mod.rs to actually include the file.

Comment (JaySon-Huang) [reply convlog/tests/testdata/confusing_nakis_7.json:1]: Added.
However, this naki won't make the program exit with error, it just doesn't show one step in the result. Adding it to convlog may not actually help us add regression test for this situation 😂
